/*
 * MainFrame.java
 *
 * Created on 16 de Mar�o de 2006, 14:30
 */

package smsrelay;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;


/**
 *
 * @author  Paul
 */
public class MainFrame extends javax.swing.JFrame {
    
    Conectar conexao=new Conectar();
    
    public DefaultListModel bdListModel;
    DefaultListModel destListModel,selListModel;
    String varTabela;

    java.lang.String StringSmsMsg;
    
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        bdListModel=new DefaultListModel(); 
        destListModel=new DefaultListModel();
        selListModel=new DefaultListModel();
        jLabelTipoCon.setText(conexao.tipoConexao());
        jLabelProxy.setText(conexao.ProxyAtivo());
        jListDest.setModel(destListModel);
        jListSel.setModel(selListModel);
    }
    
    public void CarregaGrupos(){  
        jComboBoxGrps.removeAllItems();
        if (conexao.conectado){
            Statement s;
            jComboBoxGrps.addItem("Todos os Grupos");
            try {
                s = conexao.conn.createStatement();
                s.execute("select Nome from grupos");
                ResultSet rs = s.getResultSet();
                if (rs!=null){
                    while (rs.next()){
                        //System.out.println(rs.getString(1));
                        //bdListModel.addElement(rs.getString(1)); 
                        jComboBoxGrps.addItem(rs.getString(1));                    
                    }
                }
                s.close();
                rs.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            jComboBoxGrps.addItem("Cadastrar Grupo...");
        }
    }
 
    public void CarregaUsers(int VarGrpIndex, int VarGrpItens){
        //System.out.println(VarGrpIndex);
        //System.out.println(VarGrpItens);
        destListModel.removeAllElements();    
        if (conexao.conectado){
            Statement s; 
            try {
                s = conexao.conn.createStatement();
                if (VarGrpIndex==0 || VarGrpIndex==VarGrpItens ){
                  s.execute("select * from destinatarios");
                } else {
                    s.execute("select * from destinatarios WHERE GrupoID="+VarGrpIndex);
                }
                ResultSet rs = s.getResultSet();
                if (rs!=null){
                    while (rs.next()){
                        destListModel.addElement(rs.getString(3));
                    }
                }
                s.close();
                rs.close();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }  
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOpcEnvio = new javax.swing.ButtonGroup();
        buttonGroupConfCon = new javax.swing.ButtonGroup();
        buttonGroupSolRetMsg = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDestinatarios = new javax.swing.JPanel();
        jComboBoxGrps = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDest = new javax.swing.JList();
        jBtnAddItem = new javax.swing.JButton();
        jBtnAddItens = new javax.swing.JButton();
        jBtnRemoveItem = new javax.swing.JButton();
        jBtnRemoveItens = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSel = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        JRdSendNow = new javax.swing.JRadioButton();
        jRdAgendarEnvio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelOpcAgenda = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelMsgEnvio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextMsg = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelCarDigitados = new javax.swing.JLabel();
        jLabelCarRestantes = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jConectarBtn = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelTipoCon = new javax.swing.JLabel();
        jLabelProxy = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileArquivo = new javax.swing.JMenu();
        jMenuCadastrar = new javax.swing.JMenu();
        CadUserMenuItem = new javax.swing.JMenuItem();
        CadGroupMenuItem = new javax.swing.JMenuItem();
        CadContratoMenuItem = new javax.swing.JMenuItem();
        CadEventoMenuItem = new javax.swing.JMenuItem();
        jMenuGerenciar = new javax.swing.JMenu();
        GerEventosMenuItem = new javax.swing.JMenuItem();
        GerUsuariosMenuItem = new javax.swing.JMenuItem();
        GerContratosMenuItem = new javax.swing.JMenuItem();
        GerMsgsMenuItem = new javax.swing.JMenuItem();
        AgendaMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuPropriedadesSistema = new javax.swing.JMenu();
        PropriedadesSistemaMenuItem = new javax.swing.JMenuItem();
        jMenuPropConexao = new javax.swing.JMenu();
        jRadioBtnConLocal = new javax.swing.JRadioButtonMenuItem();
        jRadioBtnConRemota = new javax.swing.JRadioButtonMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuconfCon = new javax.swing.JMenu();
        jCheckBoxProxy = new javax.swing.JCheckBoxMenuItem();
        jMenuItemConfProxy = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setName("DestinatariosTab"); // NOI18N

        jComboBoxGrps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGrpsActionPerformed(evt);
            }
        });

        jListDest.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListDest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListDest);

        jBtnAddItem.setText(">");
        jBtnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddItemActionPerformed(evt);
            }
        });

        jBtnAddItens.setText(">>");
        jBtnAddItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddItensActionPerformed(evt);
            }
        });

        jBtnRemoveItem.setText("<");
        jBtnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoveItemActionPerformed(evt);
            }
        });

        jBtnRemoveItens.setText("<<");
        jBtnRemoveItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoveItensActionPerformed(evt);
            }
        });

        jListSel.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListSel);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroupOpcEnvio.add(JRdSendNow);
        JRdSendNow.setSelected(true);
        JRdSendNow.setText("Enviar Agora");
        JRdSendNow.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        JRdSendNow.setMargin(new java.awt.Insets(0, 0, 0, 0));
        JRdSendNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRdSendNowActionPerformed(evt);
            }
        });

        buttonGroupOpcEnvio.add(jRdAgendarEnvio);
        jRdAgendarEnvio.setText("Agendar envio");
        jRdAgendarEnvio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRdAgendarEnvio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRdAgendarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdAgendarEnvioActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRdAgendarEnvio)
                    .add(JRdSendNow))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(JRdSendNow)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRdAgendarEnvio)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Agendamento");

        jPanelOpcAgenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções Agendamento"));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Data Envio:");

        jLabel4.setText("Hora:");

        jLabel5.setText("Min.:");

        jLabel6.setText(":");

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Horário Envio");

        org.jdesktop.layout.GroupLayout jPanelOpcAgendaLayout = new org.jdesktop.layout.GroupLayout(jPanelOpcAgenda);
        jPanelOpcAgenda.setLayout(jPanelOpcAgendaLayout);
        jPanelOpcAgendaLayout.setHorizontalGroup(
            jPanelOpcAgendaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOpcAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelOpcAgendaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jPanelOpcAgendaLayout.createSequentialGroup()
                        .add(jLabel4)
                        .add(49, 49, 49)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5))
                    .add(jLabel15))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanelOpcAgendaLayout.setVerticalGroup(
            jPanelOpcAgendaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOpcAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 43, Short.MAX_VALUE)
                .add(jLabel15)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelOpcAgendaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelOpcAgendaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel6)
                        .add(jLabel5))
                    .add(jPanelOpcAgendaLayout.createSequentialGroup()
                        .add(jLabel4)
                        .add(2, 2, 2)))
                .add(25, 25, 25))
        );

        org.jdesktop.layout.GroupLayout jPanelDestinatariosLayout = new org.jdesktop.layout.GroupLayout(jPanelDestinatarios);
        jPanelDestinatarios.setLayout(jPanelDestinatariosLayout);
        jPanelDestinatariosLayout.setHorizontalGroup(
            jPanelDestinatariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelDestinatariosLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelDestinatariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jComboBoxGrps, 0, 173, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelDestinatariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jBtnAddItens, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jBtnRemoveItens, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jBtnRemoveItem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jBtnAddItem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jPanelDestinatariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelDestinatariosLayout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(jPanelDestinatariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelOpcAgenda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanelDestinatariosLayout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanelDestinatariosLayout.createSequentialGroup()
                        .add(52, 52, 52)
                        .add(jLabel1)))
                .addContainerGap())
        );
        jPanelDestinatariosLayout.setVerticalGroup(
            jPanelDestinatariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelDestinatariosLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelDestinatariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelDestinatariosLayout.createSequentialGroup()
                        .add(jPanelDestinatariosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .add(jPanelDestinatariosLayout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(26, 26, 26)
                                .add(jPanelOpcAgenda, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jPanelDestinatariosLayout.createSequentialGroup()
                                .add(jComboBoxGrps, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelDestinatariosLayout.createSequentialGroup()
                        .add(jBtnAddItem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBtnAddItens, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBtnRemoveItem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBtnRemoveItens, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(39, 39, 39))))
        );

        jTabbedPane1.addTab("Destinatários", jPanelDestinatarios);

        jButton1.setText("Gravar Modelo");

        jPanelMsgEnvio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Mensagem de Envio:");

        jTextMsg.setColumns(20);
        jTextMsg.setRows(5);
        jTextMsg.setWrapStyleWord(true);
        jTextMsg.setMaximumSize(new java.awt.Dimension(150, 150));
        jTextMsg.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextMsgInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTextMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextMsgKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTextMsg);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFocusable(false);

        jLabel8.setText("Caracteres Digitados:");

        jLabelCarDigitados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCarDigitados.setText("0");

        jLabelCarRestantes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCarRestantes.setForeground(new java.awt.Color(255, 128, 0));
        jLabelCarRestantes.setText("150");

        jLabel9.setText("Caracteres Restantes:");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel9)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 55, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabelCarDigitados)
                    .add(jLabelCarRestantes))
                .add(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jLabelCarDigitados))
                .add(23, 23, 23)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jLabelCarRestantes))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanelMsgEnvioLayout = new org.jdesktop.layout.GroupLayout(jPanelMsgEnvio);
        jPanelMsgEnvio.setLayout(jPanelMsgEnvioLayout);
        jPanelMsgEnvioLayout.setHorizontalGroup(
            jPanelMsgEnvioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMsgEnvioLayout.createSequentialGroup()
                .add(jPanelMsgEnvioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelMsgEnvioLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanelMsgEnvioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane3)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanelMsgEnvioLayout.createSequentialGroup()
                        .add(70, 70, 70)
                        .add(jLabel7)))
                .addContainerGap())
        );
        jPanelMsgEnvioLayout.setVerticalGroup(
            jPanelMsgEnvioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMsgEnvioLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButton2.setText("Testar Mensagem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Tipo Mensagem:");

        jLabel11.setText("Campo Dinâmico: ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Solic. Retorno: ");

        buttonGroupSolRetMsg.add(jRadioButton1);
        jRadioButton1.setText("Sim");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroupSolRetMsg.add(jRadioButton2);
        jRadioButton2.setText("Não");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel13.setText("Número:");

        jTextField1.setText("jTextField1");

        jCheckBox1.setText("Notificar erro via SMS");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox2.setText("Notificar erro via Email");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel14.setText("Max. Tentativas Reenvio:");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jPanel4Layout.createSequentialGroup()
                                    .add(jLabel10)
                                    .add(11, 11, 11))
                                .add(jLabel11))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                                .add(jLabel12)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                                .add(jRadioButton1)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBox2, 0, 206, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4Layout.createSequentialGroup()
                                .add(jRadioButton2)
                                .add(14, 14, 14)
                                .add(jLabel13)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBox1, 0, 163, Short.MAX_VALUE))
                        .add(19, 19, 19))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel14)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jCheckBox1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jCheckBox2)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton2)
                    .add(jLabel13)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jRadioButton1)
                    .add(jLabel12))
                .add(17, 17, 17)
                .add(jLabel14)
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox1)
                    .add(jCheckBox2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)
                        .add(55, 55, 55))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jPanelMsgEnvio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelMsgEnvio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButton1)
                            .add(jButton2))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mensagem", jPanel2);

        jButton5.setText("Tray Icon");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jConectarBtn.setText("Conectar");
        jConectarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConectarBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Configurado para conexão");

        jLabelTipoCon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipoCon.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTipoCon.setText("Remota");

        jLabelProxy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelProxy.setForeground(new java.awt.Color(102, 102, 102));
        jLabelProxy.setText("....Proxy...");

        jButton3.setText("Enviar SMS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        fileArquivo.setText("Arquivo");
        fileArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileArquivoActionPerformed(evt);
            }
        });

        jMenuCadastrar.setText("Cadastro");

        CadUserMenuItem.setText("Cadastrar Usuário");
        jMenuCadastrar.add(CadUserMenuItem);

        CadGroupMenuItem.setText("Cadastrar Grupo");
        jMenuCadastrar.add(CadGroupMenuItem);

        CadContratoMenuItem.setText("Cadastrar Contrato");
        CadContratoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadContratoMenuItemActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(CadContratoMenuItem);

        CadEventoMenuItem.setText("Cadastrar Evento");
        jMenuCadastrar.add(CadEventoMenuItem);

        fileArquivo.add(jMenuCadastrar);

        jMenuGerenciar.setText("Gerenciar");

        GerEventosMenuItem.setText("Gerenciar Eventos");
        jMenuGerenciar.add(GerEventosMenuItem);

        GerUsuariosMenuItem.setText("Gerenciar Usuários");
        GerUsuariosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerUsuariosMenuItemActionPerformed(evt);
            }
        });
        jMenuGerenciar.add(GerUsuariosMenuItem);

        GerContratosMenuItem.setText("Gerenciar Contratos");
        jMenuGerenciar.add(GerContratosMenuItem);

        GerMsgsMenuItem.setText("Gerenciar Mensagens");
        jMenuGerenciar.add(GerMsgsMenuItem);

        fileArquivo.add(jMenuGerenciar);

        AgendaMenuItem.setText("Agenda");
        fileArquivo.add(AgendaMenuItem);
        fileArquivo.add(jSeparator1);

        jMenuPropriedadesSistema.setText("Configuração Sistema");

        PropriedadesSistemaMenuItem.setText("Configuração RelaySMS");
        PropriedadesSistemaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PropriedadesSistemaMenuItemActionPerformed(evt);
            }
        });
        jMenuPropriedadesSistema.add(PropriedadesSistemaMenuItem);

        jMenuPropConexao.setText("Conexão Banco de Dados");

        buttonGroupConfCon.add(jRadioBtnConLocal);
        jRadioBtnConLocal.setLabel("Banco de Dados Local");
        jRadioBtnConLocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioBtnConLocalItemStateChanged(evt);
            }
        });
        jMenuPropConexao.add(jRadioBtnConLocal);

        buttonGroupConfCon.add(jRadioBtnConRemota);
        jRadioBtnConRemota.setSelected(true);
        jRadioBtnConRemota.setLabel("Banco de Dados Remoto");
        jRadioBtnConRemota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioBtnConRemotaItemStateChanged(evt);
            }
        });
        jMenuPropConexao.add(jRadioBtnConRemota);
        jMenuPropConexao.add(jSeparator3);

        jMenuconfCon.setText("Proxy");

        jCheckBoxProxy.setText("Ativar Proxy");
        jCheckBoxProxy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxProxyItemStateChanged(evt);
            }
        });
        jMenuconfCon.add(jCheckBoxProxy);

        jMenuItemConfProxy.setText("Configurar Proxy");
        jMenuconfCon.add(jMenuItemConfProxy);

        jMenuPropConexao.add(jMenuconfCon);

        jMenuPropriedadesSistema.add(jMenuPropConexao);

        fileArquivo.add(jMenuPropriedadesSistema);
        fileArquivo.add(jSeparator2);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileArquivo.add(exitMenuItem);

        menuBar.add(fileArquivo);

        editMenu.setText("Editar");

        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText("Ajuda");

        contentsMenuItem.setText("Conteúdo");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("Sobre");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 651, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelTipoCon)
                        .add(18, 18, 18)
                        .add(jLabelProxy)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 70, Short.MAX_VALUE)
                        .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jConectarBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3)
                        .add(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabelTipoCon)
                    .add(jLabelProxy)
                    .add(jButton5)
                    .add(jConectarBtn)
                    .add(jButton3))
                .addContainerGap())
        );

        jConectarBtn.getAccessibleContext().setAccessibleName("btn_Conectar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void PropriedadesSistemaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PropriedadesSistemaMenuItemActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_PropriedadesSistemaMenuItemActionPerformed

    private void jTextMsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMsgKeyPressed
        // TODO add your handling code here:
        int TamanhoTexto, TamMaxTexto=150;
        //System.out.println(jTextMsg.getLineCount());
        //System.out.println(jTextMsg.getColumns());
        //System.out.println(jTextMsg.getRegisteredKeyStrokes());
        //System.out.println(jTextMsg.getCaretPosition());
        //StringSmsMsg=jTextMsg.getText(); 
        jLabelCarDigitados.setText(String.valueOf(jTextMsg.getCaretPosition()));
        jLabelCarRestantes.setText(StringSmsMsg.valueOf(TamMaxTexto-jTextMsg.getCaretPosition()));
        if (jTextMsg.getCaretPosition()<=80){
            jLabelCarRestantes.setForeground(new java.awt.Color(0, 153, 51));
        } else if (jTextMsg.getCaretPosition()<=120){
            jLabelCarRestantes.setForeground(new java.awt.Color(255, 128, 0));
        } else if (jTextMsg.getCaretPosition()<=150){
            jLabelCarRestantes.setForeground(new java.awt.Color(255, 0, 0));
        } else {
            jLabelCarRestantes.setText("Excedido");
        }
        //jLabelCarDigitados.setText(intToString(StringSmsMsg.length()));
        //StringSmsMsg        
    }//GEN-LAST:event_jTextMsgKeyPressed

    private void jTextMsgInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextMsgInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMsgInputMethodTextChanged

    private void JRdSendNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRdSendNowActionPerformed
        // TODO add your handling code here:
        System.out.println(JRdSendNow.isSelected());
        System.out.println(jRdAgendarEnvio.isSelected());
        //jPanelOpcAgenda.enable(false);
    }//GEN-LAST:event_JRdSendNowActionPerformed

    private void jRdAgendarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdAgendarEnvioActionPerformed
         // TODO add your handling code here:
        System.out.println(JRdSendNow.isSelected());
        System.out.println(jRdAgendarEnvio.isSelected());
        //jPanelOpcAgenda.enable(true);
        //jDateChooser1.enable(false);
        
    }//GEN-LAST:event_jRdAgendarEnvioActionPerformed

    private void jBtnRemoveItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoveItensActionPerformed
        // TODO add your handling code here:
        selListModel.removeAllElements();
    }//GEN-LAST:event_jBtnRemoveItensActionPerformed

    private void jBtnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoveItemActionPerformed
        // TODO add your handling code here:
        selListModel.removeElementAt(1);
        for (int i=0;i<=selListModel.getSize();i++){
            if (jListSel.isSelectedIndex(i)){
                selListModel.removeElementAt(i);
            }     
        }
    }//GEN-LAST:event_jBtnRemoveItemActionPerformed

    private void jBtnAddItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddItensActionPerformed
        // TODO add your handling code here:
        //System.out.println(jListDest.getSelectionMode());
        //selListModel.addElement(jListDest.getSelectedValues());
        //System.out.println(jListDest.getModel());
        
        for (int i=0; i<=destListModel.getSize(); i++){
            selListModel.addElement(destListModel.get(i));  
        }
    }//GEN-LAST:event_jBtnAddItensActionPerformed

    private void jListDestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDestMouseClicked
        // TODO add your handling code here:
        /* 
        System.out.println("click");
        System.out.println(jListDest.getModel());
        System.out.println(jListDest.getSelectedIndex());
        System.out.println(jListDest.getSelectedValue());
         */
    }//GEN-LAST:event_jListDestMouseClicked

    private void jBtnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddItemActionPerformed
        // TODO add your handling code here:
        //System.out.println(jListSel.getSelectedValue());
        //System.out.println(jListDest.getSelectedValue());
        //selListModel.addElement(jListDest.getSelectedValue());
        //System.out.println(destListModel.get(0));
        //System.out.println(destListModel.getSize());
        //System.out.println(jListDest.isSelectedIndex(0));
        for (int i=0; i<=destListModel.getSize(); i++){
            if (jListDest.isSelectedIndex(i)){
                selListModel.addElement(destListModel.get(i));    
            }
        }
        
        
    }//GEN-LAST:event_jBtnAddItemActionPerformed

    private void jComboBoxGrpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGrpsActionPerformed
        // TODO add your handling code here:
        //System.out.println(jComboBoxGrps.getSelectedItem());
        //System.out.println(jComboBoxGrps.getSelectedIndex());
        //System.out.println(jComboBoxGrps.getItemCount());
        CarregaUsers(jComboBoxGrps.getSelectedIndex(),jComboBoxGrps.getItemCount()-1);
    }//GEN-LAST:event_jComboBoxGrpsActionPerformed

    private void jCheckBoxProxyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxProxyItemStateChanged
        // TODO add your handling code here:
        System.out.println(jCheckBoxProxy.isSelected());
        if (jCheckBoxProxy.isSelected()){
            conexao.Proxy=true;
        }else {
            conexao.Proxy=false;
        }
        jLabelProxy.setText(conexao.ProxyAtivo());
    }//GEN-LAST:event_jCheckBoxProxyItemStateChanged

    private void jRadioBtnConRemotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioBtnConRemotaItemStateChanged
        // TODO add your handling code here:
        if (jRadioBtnConRemota.isSelected()){
            conexao.ConexaoLocal=false;
        }
        jLabelTipoCon.setText(conexao.tipoConexao());
    }//GEN-LAST:event_jRadioBtnConRemotaItemStateChanged

    private void jRadioBtnConLocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioBtnConLocalItemStateChanged
        // TODO add your handling code here:
        
        if (jRadioBtnConLocal.isSelected()){
            conexao.ConexaoLocal=true;
        }
        jLabelTipoCon.setText(conexao.tipoConexao());
    }//GEN-LAST:event_jRadioBtnConLocalItemStateChanged

    private void fileArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileArquivoActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_fileArquivoActionPerformed

    private void jConectarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConectarBtnActionPerformed
        // TODO add your handling code here:       
        System.out.println(Conectar.conectado);
        if (jConectarBtn.isSelected()){
            if (!Conectar.conectado){
                conexao.Conecte();
                if (conexao.conectado){
                    CarregaGrupos();
                }
                jConectarBtn.setText("Desconectar");
            } else {
                System.out.println("J� estava conectado");
            }
        } else {
            conexao.Desconecte();
            jConectarBtn.setText("Conectar");
        }
    }//GEN-LAST:event_jConectarBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            //new Tray();
            //new Conectar();
        //System.out.println(conexao.Proxy);
        //System.out.println(conexao.ProxyAtivo());
        //System.out.println(conexao.conectado);
        //new Tray();
        System.out.println("New Version");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        //System.out.println("ouch");
        AboutBoxFrame frame=new AboutBoxFrame();
        frame.setVisible(true);
        
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void GerUsuariosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerUsuariosMenuItemActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_GerUsuariosMenuItemActionPerformed

    private void CadContratoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadContratoMenuItemActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_CadContratoMenuItemActionPerformed
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgendaMenuItem;
    private javax.swing.JMenuItem CadContratoMenuItem;
    private javax.swing.JMenuItem CadEventoMenuItem;
    private javax.swing.JMenuItem CadGroupMenuItem;
    private javax.swing.JMenuItem CadUserMenuItem;
    private javax.swing.JMenuItem GerContratosMenuItem;
    private javax.swing.JMenuItem GerEventosMenuItem;
    private javax.swing.JMenuItem GerMsgsMenuItem;
    private javax.swing.JMenuItem GerUsuariosMenuItem;
    private javax.swing.JRadioButton JRdSendNow;
    private javax.swing.JMenuItem PropriedadesSistemaMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.ButtonGroup buttonGroupConfCon;
    private javax.swing.ButtonGroup buttonGroupOpcEnvio;
    private javax.swing.ButtonGroup buttonGroupSolRetMsg;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileArquivo;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jBtnAddItem;
    private javax.swing.JButton jBtnAddItens;
    private javax.swing.JButton jBtnRemoveItem;
    private javax.swing.JButton jBtnRemoveItens;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxProxy;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBoxGrps;
    private javax.swing.JToggleButton jConectarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCarDigitados;
    private javax.swing.JLabel jLabelCarRestantes;
    private javax.swing.JLabel jLabelProxy;
    private javax.swing.JLabel jLabelTipoCon;
    private javax.swing.JList jListDest;
    private javax.swing.JList jListSel;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenu jMenuGerenciar;
    private javax.swing.JMenuItem jMenuItemConfProxy;
    private javax.swing.JMenu jMenuPropConexao;
    private javax.swing.JMenu jMenuPropriedadesSistema;
    private javax.swing.JMenu jMenuconfCon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDestinatarios;
    private javax.swing.JPanel jPanelMsgEnvio;
    private javax.swing.JPanel jPanelOpcAgenda;
    private javax.swing.JRadioButtonMenuItem jRadioBtnConLocal;
    private javax.swing.JRadioButtonMenuItem jRadioBtnConRemota;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRdAgendarEnvio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea jTextMsg;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables
    
}
